server:
  port: 8080
debug: true
spring:
  devtools:
    restart:
      enabled: true
  freemarker:
    cache: false
  mvc:
    view:
      prefix: /
      suffix: .html
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/admin?connectTimeout=1000&socketTimeout=12000&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
    data-username: root
    data-password: 123456
mybatis:
  type-aliases-package: com.yxyxy.model
  mapper-locations: classpath:mapper/*.xml
